"""Host protocol checks; Java/JNI, Android cookies and cancellation need device tests."""
import importlib.util
import json
from pathlib import Path
import sys
import types
import unittest
from unittest.mock import Mock, patch
from urllib.parse import parse_qs, urlsplit

# Tests import the production files directly; keep generated bytecode out of assets.
sys.dont_write_bytecode = True

ROOT = Path(__file__).resolve().parents[2] / "main" / "python"


class File:
    def __init__(self, path):
        self.path = path

    def getAbsolutePath(self):
        return self.path


class Element:
    def __init__(self, value):
        self.value = value

    def getAsJsonObject(self):
        if not isinstance(self.value, dict):
            raise ValueError("object required")
        return self.value


class Result:
    def __init__(self, data):
        self.data = data
        self.settings = None

    def json(self, settings):
        self.settings = settings
        return json.dumps(self.data)


class Native:
    def __init__(self):
        self.calls = []
        self.response = {"code": 200, "content": "body"}
        self.json_value = {"名称": "示范", "items": [1, False, None]}
        self.values = {}
        self.closed = 0
        self.child = None
        self.refresh_loader = None
        self.batch_results = []

    def req(self, url, options):
        self.calls.append(("req", url, json.loads(options)))
        return json.dumps(self.response)

    def ws(self, url, options):
        self.calls.append(("ws", url, json.loads(options)))
        return json.dumps(self.response)

    def json(self, url, options):
        self.calls.append(("json", url, json.loads(options)))
        return json.dumps(self.json_value)

    def get(self, url):
        self.calls.append(("get", url))
        return "direct-body"

    def batch(self, requests, limit):
        self.calls.append(("batch", json.loads(requests), limit))
        return self.batch_results

    def cached(self, key, options, loader):
        self.calls.append(("cached", key, json.loads(options)))
        self.values[key] = loader.call()
        return self.values[key]

    def peek(self, key):
        return self.values.get(key)

    def refresh(self, key, options, loader):
        self.calls.append(("refresh", key, json.loads(options)))
        self.refresh_loader = loader

    def clearCache(self, *args):
        self.calls.append(("clear", args))
        if args:
            self.values.pop(args[0], None)
        else:
            self.values.clear()

    def download(self, url, options, file):
        self.calls.append(("download", url, json.loads(options), file.path))

    def getCookie(self, url):
        return "sid=one"

    def setCookie(self, url, value):
        self.calls.append(("cookie", url, value))
        return True

    def sleep(self, value):
        self.calls.append(("sleep", value))

    def session(self):
        self.child = Native()
        return self.child

    def close(self):
        self.closed += 1


class NativeLocal:
    def __init__(self):
        self.values = {}

    def get(self, key):
        return self.values.get(key)

    def set(self, key, value):
        self.values[key] = value

    def delete(self, key):
        self.values.pop(key, None)

    def clear(self):
        self.values.clear()


class SpiderApiTest(unittest.TestCase):
    def setUp(self):
        self.activity = object()
        init = types.SimpleNamespace(activity=lambda: self.activity,
                                     context=lambda: types.SimpleNamespace(getCacheDir=lambda: File("/cache")))
        options = types.SimpleNamespace()
        setattr(options, "from", json.loads)
        classes = {
            "java.util.concurrent.Callable": object,
            "java.io.File": File,
            "com.github.catvod.Init": init,
            "com.github.catvod.net.NetOptions": options,
            "com.github.catvod.utils.Util": types.SimpleNamespace(CHROME="host-test-UA"),
            "com.google.gson.JsonParser": types.SimpleNamespace(parseString=lambda value: Element(json.loads(value))),
            "com.github.catvod.utils.Json": types.SimpleNamespace(link=lambda name, target: "[a=cr:" + json.dumps(target, ensure_ascii=False, separators=(",", ":")) + "/]" + name + "[/a]"),
        }
        modules = {name: types.ModuleType(name) for name in ["java", "requests", "lxml", "com", "com.github", "com.github.catvod", "com.chaquo", "com.chaquo.python", "base"]}
        modules["java"].jclass = lambda name: classes[name]
        modules["java"].dynamic_proxy = lambda *_: object
        modules["requests"].get = Mock(return_value=types.SimpleNamespace(encoding=None, text="legacy", headers={}))
        modules["requests"].post = Mock(return_value=types.SimpleNamespace(encoding=None, text="legacy", headers={}))
        modules["lxml"].etree = types.SimpleNamespace(HTML=lambda text: text)
        modules["com.github.catvod"].Init = init
        modules["com.github.catvod"].Proxy = types.SimpleNamespace(getUrl=lambda local: "http://" + ("127.0.0.1" if local else "192.0.2.1") + ":9978/proxy", getPort=lambda: 9978)
        modules["com.chaquo.python"].Python = object
        modules["base"].__path__ = [str(ROOT / "base")]
        self.patch = patch.dict(sys.modules, modules)
        self.patch.start()
        self.addCleanup(self.patch.stop)
        self.requests = modules["requests"]
        self.net_module = self.load("base.net", ROOT / "base" / "net.py")
        self.spider_module = self.load("base.spider", ROOT / "base" / "spider.py")
        self.app = self.load("test_python_app", ROOT / "app.py")
        self.native = Native()
        self.net = self.net_module.Net(self.native)
        self.native_local = NativeLocal()
        self.local = self.net_module.Local(self.native_local)

    def load(self, name, path):
        spec = importlib.util.spec_from_file_location(name, path)
        module = importlib.util.module_from_spec(spec)
        sys.modules[name] = module
        spec.loader.exec_module(module)
        return module

    def spider(self):
        base = self.spider_module.Spider

        class Concrete(base):
            def init(self, extend=""):
                pass

        value = Concrete()
        value.siteKey = "site & 中文"
        return value

    def test_legacy_fetch_post_keep_requests_options_and_response(self):
        spider = self.spider()
        self.net_module.bind(spider, self.native, self.native_local)
        result = spider.fetch("https://example.test", params={"page": 2}, cookies={"sid": "v"}, headers={"X": "Y"}, timeout=7, verify=False, stream=True, allow_redirects=False)
        self.assertIs(result, self.requests.get.return_value)
        self.assertEqual(result.encoding, "utf-8")
        self.requests.get.assert_called_once_with("https://example.test", params={"page": 2}, cookies={"sid": "v"}, headers={"X": "Y"}, timeout=7, verify=False, stream=True, allow_redirects=False)
        spider.post("https://example.test", data={"a": "b"}, json={"v": 1}, timeout=9)
        self.assertEqual(self.requests.post.call_args.kwargs["data"], {"a": "b"})
        self.assertEqual(self.requests.post.call_args.kwargs["json"], {"v": 1})
        self.assertEqual(self.requests.post.call_args.kwargs["timeout"], 9)
        self.assertEqual(self.native.calls, [])

    def test_proxy_boolean_overload_and_new_encoded_site_parameters(self):
        spider = self.spider()
        self.assertEqual(spider.getProxyUrl(True), "http://127.0.0.1:9978/proxy?do=py")
        self.assertEqual(spider.getProxyUrl(False), "http://192.0.2.1:9978/proxy?do=py")
        self.assertEqual(spider.getProxyUrl(local=False), "http://192.0.2.1:9978/proxy?do=py")
        query = parse_qs(urlsplit(spider.getProxyUrl({"url": "https://example.test/a?q=x&n=中"})).query)
        self.assertEqual(query["siteKey"], ["site & 中文"])
        self.assertEqual(query["url"], ["https://example.test/a?q=x&n=中"])
        for reserved in ["do", "siteKey"]:
            with self.assertRaises(ValueError):
                spider.getProxyUrl({reserved: "wrong"})

    def test_bind_preserves_custom_names_and_refreshes_only_own_adapters(self):
        custom_net, custom_local = object(), {}
        spider = types.SimpleNamespace(net=custom_net, local=custom_local)
        self.net_module.bind(spider, self.native, self.native_local)
        self.assertIs(spider.net, custom_net)
        self.assertIs(spider.local, custom_local)
        spider = types.SimpleNamespace(net=None)
        self.app.bind(spider, self.native, self.native_local)
        self.assertIs(spider.net._native, self.native)
        self.assertIs(spider.local._native, self.native_local)
        replacement = Native()
        self.net_module.bind(spider, replacement, self.native_local)
        self.assertIs(spider.net._native, replacement)

    def test_native_json_and_binary_responses_keep_types(self):
        self.assertEqual(self.net.json("url", {"params": {"名称": "a&b"}}), self.native.json_value)
        self.assertEqual(self.native.calls[-1][2], {"params": {"名称": "a&b"}})
        self.native.response = {"code": 200, "content": [-128, -1, 0, 127]}
        self.assertEqual(self.net.req("url", {"buffer": 3})["content"], b"\x80\xff\x00\x7f")
        self.assertEqual(self.net.ws("url", {"buffer": 3})["content"], b"\x80\xff\x00\x7f")
        self.assertEqual(self.net.req("url", {"buffer": 1})["content"], [-128, -1, 0, 127])

    def test_batch_uses_each_requests_buffer_mode(self):
        self.native.batch_results = [Result({"code": 200, "content": [-1]}), Result({"code": 404, "content": "missing"})]
        result = self.net.batch([{"url": "one", "options": {"buffer": 3}}, {"url": "two"}], 2)
        self.assertEqual(result[0]["content"], b"\xff")
        self.assertEqual(result[1], {"code": 404, "content": "missing"})
        self.assertEqual(self.native.batch_results[0].settings, {"buffer": 3})

    def test_cache_callable_round_trip_and_rejects_non_json_values(self):
        value = {"items": [1, False, None], "名称": "缓存"}
        self.assertEqual(self.net.cached("key", {"ttl": 1000}, lambda: value), value)
        self.assertEqual(self.net.peek("key"), value)
        called = []
        self.net.refresh("key", {"ttl": 1}, lambda: called.append(True) or value)
        self.assertEqual(called, [])
        self.assertEqual(json.loads(self.native.refresh_loader.call()), value)
        self.assertEqual(called, [True])
        with self.assertRaises(ValueError):
            self.net.cached("bad", {"ttl": 1}, lambda: float("nan"))
        with self.assertRaises(TypeError):
            self.net.cached("bad", {"ttl": 1}, lambda: b"bytes")
        self.net.clearCache("key")
        self.assertIsNone(self.net.peek("key"))
        self.net.clearCache()
        self.assertEqual(self.native.calls[-1], ("clear", ()))

    def test_local_and_http_cache_are_separate_json_stores(self):
        value = [1, False, None, {"k": "中文"}]
        self.local.set("key", value)
        self.net.clearCache()
        self.assertEqual(self.local.get("key"), value)
        self.local.delete("key")
        self.assertIsNone(self.local.get("key"))
        self.local.set("other", None)
        self.assertEqual(self.native_local.values["other"], "null")
        self.local.clear()
        self.assertEqual(self.native_local.values, {})

    def test_session_context_manager_closes_on_exception(self):
        with self.assertRaisesRegex(RuntimeError, "application failure"):
            with self.net.session() as session:
                self.assertIs(session._native, self.native.child)
                raise RuntimeError("application failure")
        self.assertEqual(self.native.child.closed, 1)
        self.assertEqual(self.native.closed, 0)

    def test_download_relative_paths_and_cookie_user_agent_delegation(self):
        self.assertEqual(self.net.download("url", Path("spider/file.bin"), {"timeout": 9}), "/cache/spider/file.bin")
        self.assertEqual(self.native.calls[-1], ("download", "url", {"timeout": 9}, "/cache/spider/file.bin"))
        self.assertEqual(self.net.getCookie("url"), "sid=one")
        self.assertTrue(self.net.setCookie("url", "sid=two"))
        self.assertEqual(self.net.getUserAgent(), "host-test-UA")

    def test_page_link_and_activity_helpers_match_native_value_shapes(self):
        spider = self.spider()
        self.assertEqual(spider.page([1, 2, 3, 4, 5], "2", 2), {"list": [3, 4], "page": 2, "pagecount": 3, "limit": 2, "total": 5})
        with self.assertRaises(ValueError):
            spider.page([1], 0, 2)
        self.assertIs(spider.getActivity(), self.activity)
        expected = '[a=cr:{"id":"中文"}/]name[/a]'
        self.assertEqual(spider.link("name", {"id": "中文"}), expected)
        self.assertEqual(self.spider_module.Spider.link("name", {"id": "中文"}), expected)

    def test_live_bridge_serializes_objects_and_preserves_text(self):
        source = types.SimpleNamespace(liveContent=lambda _: [{"name": "line", "channel": []}])
        self.assertEqual(json.loads(self.app.liveContent(source, "url")), [{"name": "line", "channel": []}])
        source.liveContent = lambda _: "#EXTM3U\nurl"
        self.assertEqual(self.app.liveContent(source, "url"), "#EXTM3U\nurl")


if __name__ == "__main__":
    unittest.main()
